apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "opentelemetry-operator-system/demo-instrumentation"  # specify namespace and name
    spec:
      containers:
      - name: weatherapi-container
        image: ahassanop5/weatherapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
