apiVersion: v1
kind: Service
metadata:
  name: weatherapi-service
spec:
  selector:
    app: weatherapi    # Make sure this matches your deployment's label
  ports:
    - protocol: TCP
      port: 8080       # Service port (forwarded to your app)
      targetPort: 8080 # The port your application listens to inside the pod
  type: ClusterIP      # No need for NodePort; ClusterIP is sufficient for port-forwarding